/* AUTO-EXTRACTED from the vanilla build. */
// @ts-nocheck
export const GLOSS_GROUPS = [
 {id:"discipline", name:"The discipline & roles"},
 {id:"mobilization", name:"Mobilization & resistance"},
 {id:"human", name:"The human journey"},
 {id:"delivery", name:"Delivery, measurement & anchoring"}
];

export const GLOSS = [
 {g:"discipline", en:"Change management", fr:"Conduite du changement", p:"The discipline of moving people and organizations from a current state to a desired one. FR usage strongly prefers 'conduite' (steering) over the literal 'gestion'.", pf:"La discipline qui conduit personnes et organisations d'un état actuel vers un état visé. L'usage français préfère nettement « conduite » (piloter) à la traduction littérale « gestion »."},
 {g:"discipline", en:"Change vs transition", fr:"Changement vs transition", p:"Bridges' core distinction: change is the external event (new system, new org chart); transition is the internal, psychological journey through it. You can install a change in a day; the transition takes as long as it takes.", pf:"La distinction fondatrice de Bridges : le changement est l'événement externe (nouveau système, nouvel organigramme) ; la transition est le trajet psychologique interne. On installe un changement en un jour ; la transition prend le temps qu'elle prend."},
 {g:"discipline", en:"Sponsor", fr:"Sponsor / Porteur du changement", p:"The executive who owns the change publicly, pays for it politically, and defends it at cost. French practice keeps 'sponsor'; 'porteur' appears in formal documents.", pf:"Le dirigeant qui porte le changement publiquement, le paie politiquement et le défend à ses frais. La pratique française garde « sponsor » ; « porteur » figure dans les documents formels."},
 {g:"discipline", en:"Sponsorship", fr:"Portage / Sponsoring", p:"Not a title but a set of behaviors: speaking about the change unprompted, arbitrating in its favor, spending political capital. The single strongest predictor of success or failure.", pf:"Pas un titre : un ensemble de comportements. Parler du changement sans y être invité, arbitrer en sa faveur, dépenser du capital politique. Le prédicteur de succès ou d'échec le plus puissant."},
 {g:"discipline", en:"Stakeholder", fr:"Partie prenante", p:"Anyone who affects or is affected by the change. The map of who they are, what they can do to you and what they need from you is the first artifact of any serious engagement.", pf:"Toute personne qui affecte le changement ou en est affectée. La carte de qui elles sont, de ce qu'elles peuvent vous faire et de ce dont elles ont besoin est le premier artefact d'une mission sérieuse."},
 {g:"discipline", en:"Stakeholder mapping", fr:"Cartographie des parties prenantes", p:"Positioning stakeholders on power × attitude to derive an engagement move per quadrant: mobilize the champions, convince the powerful skeptics, inform the rest.", pf:"Positionner les parties prenantes sur pouvoir × attitude pour en déduire un geste d'engagement par quadrant : mobiliser les champions, convaincre les sceptiques puissants, informer le reste."},
 {g:"discipline", en:"Change agent", fr:"Acteur / Agent du changement", p:"Anyone formally tasked with making the change happen: practitioners, project members, consultants. Distinct from relays, who act from within the affected teams.", pf:"Toute personne formellement chargée de faire advenir le changement : praticiens, équipe projet, consultants. Distinct des relais, qui agissent de l'intérieur des équipes concernées."},
 {g:"discipline", en:"Change champion / relay", fr:"Relais du changement / Ambassadeur", p:"A respected insider who carries the change within their own team. Chosen for credibility, not enthusiasm: a converted skeptic is worth ten volunteers.", pf:"Un initié respecté qui porte le changement dans sa propre équipe. Choisi pour sa crédibilité, pas son enthousiasme : un sceptique converti vaut dix volontaires."},
 {g:"discipline", en:"Change portfolio", fr:"Portefeuille des changements", p:"The full inventory of changes hitting a population at once. Unmanaged, it silently exceeds absorption capacity; managing it is a governance act, not a communication one.", pf:"L'inventaire complet des changements qui frappent une population en même temps. Non géré, il dépasse silencieusement la capacité d'absorption ; le gérer est un acte de gouvernance, pas de communication."},
 {g:"discipline", en:"Steering committee", fr:"Comité de pilotage (COPIL)", p:"The governance body that arbitrates, unblocks and holds the change accountable. The French 'COPIL' is universal in francophone organizations.", pf:"L'organe de gouvernance qui arbitre, débloque et tient le changement responsable. Le « COPIL » est universel dans les organisations francophones."},
 {g:"discipline", en:"Root cause", fr:"Cause racine", p:"What is actually broken, as opposed to what hurts. Symptoms get stated; root causes get discovered, usually somewhere in incentives, decision rights or identity.", pf:"Ce qui est réellement cassé, par opposition à ce qui fait mal. Les symptômes s'énoncent ; les causes racines se découvrent, en général du côté des incitations, des droits de décision ou de l'identité."},
 {g:"discipline", en:"Five whys", fr:"Les cinq pourquoi", p:"Asking 'why' repeatedly (about five times) to walk from symptom to root cause. Stop when you reach something nobody wants written down; that is usually it.", pf:"Demander « pourquoi » environ cinq fois pour remonter du symptôme à la cause. S'arrêter quand on atteint ce que personne ne veut voir écrit : c'est en général ça."},

 {g:"mobilization", en:"Buy-in", fr:"Adhésion", p:"Genuine acceptance, not compliance. 'Adhésion' carries it well in French; mixed teams still say 'buy-in'.", pf:"L'acceptation réelle, pas la conformité. « Adhésion » le porte bien ; les équipes mixtes disent encore « buy-in »."},
 {g:"mobilization", en:"Sense of urgency", fr:"Sentiment d'urgence", p:"Kotter's step 1: the shared, visceral conviction that the status quo is more dangerous than the change. Urgency is what leaders do when nobody is watching, not what the kickoff slides say.", pf:"L'étape 1 de Kotter : la conviction partagée et viscérale que le statu quo est plus dangereux que le changement. L'urgence, c'est ce que font les dirigeants quand personne ne regarde."},
 {g:"mobilization", en:"Burning platform", fr:"Burning platform (non traduit)", p:"The metaphor for a survival-level case for change. French practice keeps the English term. Handle with care: a burning platform motivates escape, not destination.", pf:"La métaphore d'un dossier de changement au niveau de la survie. La pratique française garde l'anglais. À manier avec soin : une plateforme en feu motive la fuite, pas la destination."},
 {g:"mobilization", en:"Guiding coalition", fr:"Coalition directrice", p:"Kotter's step 2: the group with enough power, expertise and credibility to lead the change. A coalition without a converted skeptic convinces no one.", pf:"L'étape 2 de Kotter : le groupe avec assez de pouvoir, d'expertise et de crédibilité pour conduire le changement. Une coalition sans sceptique converti ne convainc personne."},
 {g:"mobilization", en:"Quick win", fr:"Victoire rapide", p:"A visible, unambiguous early success, engineered by design into the first months, never left to hope. Franglais 'quick win' dominates in French practice.", pf:"Un succès précoce, visible, sans ambiguïté, fabriqué à dessein dans les premiers mois, jamais laissé à l'espoir. Le franglais « quick win » domine la pratique."},
 {g:"mobilization", en:"WIIFM", fr:"« Qu'est-ce que j'y gagne ? »", p:"'What's In It For Me': the individual-level answer every change must provide. If the honest answer is 'nothing, and here is why we still must', say that; invented benefits cost credibility.", pf:"« Qu'est-ce que j'y gagne ? » : la réponse individuelle que tout changement doit fournir. Si la réponse honnête est « rien, et voici pourquoi il faut quand même », dites-le ; les bénéfices inventés coûtent du crédit."},
 {g:"mobilization", en:"Resistance", fr:"Résistance", p:"Information wearing an unpleasant coat. Usually rational from where the resister stands: treat it as data about what the diagnosis missed, not as an enemy to defeat.", pf:"De l'information dans un manteau désagréable. Le plus souvent rationnelle depuis la position du résistant : la traiter comme une donnée sur ce que le diagnostic a manqué, pas comme un ennemi."},
 {g:"mobilization", en:"Frozen middle", fr:"Encadrement intermédiaire figé", p:"The middle management layer that nods in meetings and changes nothing on the floor. Usually rational: they absorb the workload of every change and are the last consulted. Never use the term in a deck they might see.", pf:"L'encadrement intermédiaire qui approuve en réunion et ne change rien sur le terrain. Le plus souvent rationnel : il absorbe la charge de chaque changement et il est consulté en dernier. Ne jamais employer le terme dans un support qu'il pourrait voir."},
 {g:"mobilization", en:"Malicious compliance", fr:"Conformité de façade / Obéissance malicieuse", p:"Implementing the letter of the change in the most useless possible way. The signature risk of imposed change with zero Desire.", pf:"Appliquer la lettre du changement de la façon la plus inutile possible. Le risque signature du changement subi à Volonté nulle."},
 {g:"mobilization", en:"Informal organization", fr:"Organisation informelle", p:"The coffee-machine network: who actually influences whom, regardless of the org chart. Diagnosing only the formal structure misses where adoption is really decided.", pf:"Le réseau de la machine à café : qui influence réellement qui, organigramme mis à part. Ne diagnostiquer que la structure formelle, c'est manquer l'endroit où l'adoption se décide."},

 {g:"human", en:"Change curve", fr:"Courbe du changement", p:"The emotional arc through imposed change, adapted from Kübler-Ross: shock, frustration, the valley, experimentation, integration. A reading instrument, never a device for labeling individuals.", pf:"L'arc émotionnel du changement subi, adapté de Kübler-Ross : choc, frustration, vallée, expérimentation, intégration. Un instrument de lecture, jamais un outil d'étiquetage des individus."},
 {g:"human", en:"Valley of change", fr:"Vallée du changement", p:"The low point of the curve: old competence gone, new competence not yet built. Normal and temporary; panic reactions to it cause more damage than the valley itself.", pf:"Le point bas de la courbe : l'ancienne compétence a disparu, la nouvelle n'existe pas encore. Normal et temporaire ; ce sont les réactions de panique qui font les dégâts."},
 {g:"human", en:"Endings", fr:"Deuils / Fins (Bridges)", p:"Bridges' first phase: naming and honoring what people lose (competence, status, relationships, identity) before asking them to begin. What is not grieved is carried into the new world.", pf:"La première phase de Bridges : nommer et honorer ce que les gens perdent (compétence, statut, relations, identité) avant de leur demander de commencer. Ce qui n'est pas pleuré est emporté dans le nouveau monde."},
 {g:"human", en:"Neutral zone", fr:"Zone neutre", p:"Bridges' in-between: the old is gone, the new is not yet real. Anxious, foggy, and paradoxically the most creative phase, if given temporary structure instead of being rushed.", pf:"L'entre-deux de Bridges : l'ancien a disparu, le nouveau n'est pas encore réel. Anxieux, flou, et paradoxalement la phase la plus créative si on lui donne une structure temporaire au lieu de la précipiter."},
 {g:"human", en:"New beginnings (4 P's)", fr:"Nouveaux départs (les 4 P)", p:"Bridges' third phase, activated by Purpose, Picture, Plan and Part: people commit when they know why, can see it, know the path, and have a role in it.", pf:"La troisième phase de Bridges, activée par Purpose, Picture, Plan, Part : on s'engage quand on connaît le pourquoi, qu'on peut le voir, qu'on connaît le chemin et qu'on y a un rôle."},
 {g:"human", en:"Change fatigue", fr:"Fatigue / Saturation du changement", p:"Exhaustion from accumulated, overlapping changes. Not resistance: a capacity problem. The treatment is portfolio management and visible finishing, not motivation campaigns.", pf:"L'épuisement des changements accumulés et superposés. Pas de la résistance : un problème de capacité. Le traitement est la gestion de portefeuille et le fait de terminer visiblement, pas les campagnes de motivation."},
 {g:"human", en:"Absorption capacity", fr:"Capacité d'absorption", p:"How much change a population can genuinely metabolize per period, on top of the day job. A finite budget that most organizations spend without accounting.", pf:"Ce qu'une population peut réellement métaboliser de changement par période, en plus du travail quotidien. Un budget fini que la plupart des organisations dépensent sans comptabilité."},
 {g:"human", en:"Scar tissue", fr:"Cicatrices du changement", p:"What past changes left behind: broken promises remembered, initiatives that died, cynicism earned. The best predictor of how the next change will be received.", pf:"Ce que les changements passés ont laissé : promesses rompues mémorisées, initiatives mortes, cynisme mérité. Le meilleur prédicteur de l'accueil du prochain changement."},
 {g:"human", en:"Survivor syndrome", fr:"Syndrome du survivant", p:"The guilt, fear and disengagement of those who remain after layoffs. Invisible in dashboards, decisive in performance; treated by acknowledgment, never by exhortation.", pf:"La culpabilité, la peur et le désengagement de ceux qui restent après des licenciements. Invisible dans les tableaux de bord, décisif dans la performance ; se traite par la reconnaissance, jamais par l'exhortation."},
 {g:"human", en:"Psychological safety", fr:"Sécurité psychologique", p:"The shared belief that speaking up (doubts, errors, bad news) is not punished. Without it, every pulse survey and every standup returns fiction.", pf:"La croyance partagée que s'exprimer (doutes, erreurs, mauvaises nouvelles) n'est pas puni. Sans elle, chaque sondage de pouls et chaque standup renvoient de la fiction."},

 {g:"delivery", en:"Readiness", fr:"Maturité au changement", p:"The organization's capacity to absorb a given change now: sponsorship, capacity, culture, history, clarity. Measured as a profile, never a single magic number.", pf:"La capacité de l'organisation à absorber un changement donné, maintenant : portage, capacité, culture, historique, clarté. Mesurée comme un profil, jamais comme un chiffre magique."},
 {g:"delivery", en:"Impact assessment", fr:"Étude d'impact", p:"Who changes what in their daily work, and how much. The bridge between the project plan ('what we deploy') and the change plan ('what we ask of whom').", pf:"Qui change quoi dans son travail quotidien, et à quel point. Le pont entre le plan projet (« ce qu'on déploie ») et le plan de changement (« ce qu'on demande à qui »)."},
 {g:"delivery", en:"Unfreeze / refreeze", fr:"Décristallisation / Recristallisation", p:"Lewin's opening and closing moves: destabilize the current equilibrium, then deliberately stabilize the new one. French academic literature uses the crystallization terms; practitioners often keep the English.", pf:"Les gestes d'ouverture et de fermeture de Lewin : déstabiliser l'équilibre actuel, puis stabiliser délibérément le nouveau. La littérature académique française parle de décristallisation / recristallisation ; les praticiens gardent souvent l'anglais."},
 {g:"delivery", en:"Force field analysis", fr:"Analyse du champ de forces", p:"Lewin's tool: map the driving and restraining forces around a change. Weakening one restraint usually beats adding three drivers.", pf:"L'outil de Lewin : cartographier les forces motrices et les forces de retenue autour d'un changement. Affaiblir une retenue bat en général l'ajout de trois moteurs."},
 {g:"delivery", en:"Barrier point", fr:"Point de blocage", p:"In ADKAR practice, the first element where a person or population is stuck (Awareness, Desire, Knowledge, Ability or Reinforcement). Treat that one; everything downstream waits.", pf:"Dans la pratique ADKAR, le premier élément où une personne ou une population est bloquée (Conscience, Volonté, Savoir, Capacité, Renforcement). Traiter celui-là ; tout l'aval attend."},
 {g:"delivery", en:"Awareness / Desire", fr:"Conscience du besoin / Volonté", p:"ADKAR's first two elements: knowing why the change is needed, then personally deciding to engage. Desire is the only element that cannot be mandated or trained.", pf:"Les deux premiers éléments d'ADKAR : savoir pourquoi le changement est nécessaire, puis décider personnellement de s'engager. La Volonté est le seul élément qu'on ne peut ni décréter ni former."},
 {g:"delivery", en:"Adoption", fr:"Adoption", p:"Are people actually doing the new thing? The first of the three honest metrics. Logins and training completions are not adoption.", pf:"Les gens font-ils réellement la nouvelle chose ? La première des trois métriques honnêtes. Les connexions et les formations complétées ne sont pas de l'adoption."},
 {g:"delivery", en:"Proficiency", fr:"Maîtrise", p:"Are they doing it well? Demonstrated performance in real conditions, the second honest metric. The gap between adoption and proficiency is where benefits leak.", pf:"Le font-ils bien ? La performance démontrée en conditions réelles, la deuxième métrique honnête. L'écart entre adoption et maîtrise est là où fuient les bénéfices."},
 {g:"delivery", en:"Sustainment", fr:"Pérennisation", p:"Still doing it at month six, without the project team in the room? The third honest metric and the only one that proves the change is real.", pf:"Le font-ils encore au sixième mois, sans l'équipe projet dans la pièce ? La troisième métrique honnête et la seule qui prouve que le changement est réel."},
 {g:"delivery", en:"Reinforcement", fr:"Renforcement", p:"ADKAR's fifth element and the most neglected: recognition, measurement, incentive alignment and relapse correction that make the new way stick.", pf:"Le cinquième élément d'ADKAR et le plus négligé : reconnaissance, mesure, alignement des incitations et correction des rechutes qui font tenir la nouvelle façon."},
 {g:"delivery", en:"Anchoring", fr:"Ancrage", p:"Wiring the change into systems that outlive the project: hiring, promotion, incentives, onboarding, rituals. Kotter's step 8; where transformations are won or quietly lost.", pf:"Câbler le changement dans des systèmes qui survivent au projet : recrutement, promotion, incitations, intégration, rituels. L'étape 8 de Kotter ; là où les transformations se gagnent ou se perdent en silence."},
 {g:"delivery", en:"Pilot", fr:"Pilote", p:"The first real deployment, run with a credible-but-friendly population. Not the enthusiasts: nobody believes their success.", pf:"Le premier déploiement réel, mené avec une population crédible-mais-favorable. Pas les enthousiastes : personne ne croit à leur succès."},
 {g:"delivery", en:"Big bang vs waves", fr:"Big bang vs déploiement par vagues", p:"Deploying everywhere at once versus in sequenced waves. Waves trade speed for learning and momentum; big bangs trade everything for a date.", pf:"Déployer partout d'un coup contre des vagues séquencées. Les vagues échangent la vitesse contre l'apprentissage et l'élan ; le big bang échange tout contre une date."},
 {g:"delivery", en:"Go-live & hypercare", fr:"Mise en production & hypercare", p:"The switch-on moment and the reinforced-support period right after. Where project teams celebrate and change teams start counting: go-live is the beginning of adoption, not the end of the change.", pf:"Le moment de bascule et la période de support renforcé qui suit. Là où les équipes projet célèbrent et où les équipes du changement commencent à compter : la mise en production est le début de l'adoption, pas la fin du changement."}
];

export const GLOSS_GROUPS_FR = {
 discipline:"La discipline & les rôles", mobilization:"Mobilisation & résistance",
 human:"Le trajet humain", delivery:"Déploiement, mesure & ancrage"
};
