/* AUTO-EXTRACTED from the vanilla build. */
// @ts-nocheck
export const PHASES=[
 {n:"Frame the problem",obj:"Translate what the client says into what's actually broken.",act:"Sponsor interviews, five-whys discipline, success defined as observable outcomes, change typing (transformational / transitional / developmental; imposed / chosen).",tool:"Change Definition Canvas",del:"One-page Change Brief, sponsor-signed",dur:"1–3 weeks",mis:"Accepting the client's self-diagnosis: clients bring solutions disguised as problems."},
 {n:"Diagnose the terrain",obj:"Know the ground before choosing weapons.",act:"Readiness diagnostic, stakeholder mapping (power × attitude), culture scan, sponsorship strength test, history audit of the last three changes.",tool:"Readiness instrument + Stakeholder Map",del:"Readiness Profile + risk map",dur:"2–4 weeks",mis:"Diagnosing structures and forgetting the informal organization; the coffee-machine network decides."},
 {n:"Select & assemble",obj:"Map findings to framework components, never whole frameworks.",act:"Apply the assembly matrix: one spine framework (Kotter arc or ADKAR tracking), targeted grafts, maximum three sources.",tool:"Assembly Matrix",del:"Tailored Change Playbook",dur:"1–2 weeks",mis:"Framework maximalism: deploying all eight Kotter steps when diagnosis showed only two were missing."},
 {n:"Apply in waves",obj:"Momentum before coverage.",act:"Pilot with a credible-but-friendly population, quick wins engineered into the first 60 days, governance cadence, resistance treated as data.",tool:"Wave plan + risk log",del:"Execution roadmap, living",dur:"3–9 months",mis:"The big-bang launch with a communication 'campaign' instead of a conversation architecture."},
 {n:"Anchor & measure",obj:"Make it survive your departure.",act:"Adoption / proficiency / sustainability metrics, incentives and rituals rewired, capability transferred to internal relays.",tool:"Adoption dashboard",del:"Anchoring plan + capability handover",dur:"2–4 months",mis:"Declaring victory at go-live. Month-six measurement is the real verdict."}
];

export const PH_FR=[
 {n:"Cadrer le problème",obj:"Traduire ce que le client dit en ce qui est réellement cassé.",act:"Entretiens sponsor, discipline des cinq pourquoi, succès défini en résultats observables, typologie du changement (transformationnel / transitionnel / développemental ; subi / choisi).",tool:"Canevas de définition du changement",del:"Brief du changement d'une page, signé par le sponsor",dur:"1 à 3 semaines",mis:"Accepter l'autodiagnostic du client : les clients apportent des solutions déguisées en problèmes."},
 {n:"Diagnostiquer le terrain",obj:"Connaître le terrain avant de choisir les armes.",act:"Diagnostic de maturité, cartographie des parties prenantes (pouvoir × attitude), scan culturel, test de solidité du portage, audit historique des trois derniers changements.",tool:"Instrument de maturité + carte des parties prenantes",del:"Profil de maturité + carte des risques",dur:"2 à 4 semaines",mis:"Diagnostiquer les structures en oubliant l'organisation informelle : c'est le réseau de la machine à café qui décide."},
 {n:"Sélectionner & assembler",obj:"Relier les constats aux composants des cadres, jamais aux cadres entiers.",act:"Appliquer la matrice d'assemblage : un cadre-colonne (arc Kotter ou suivi ADKAR), des greffes ciblées, trois sources maximum.",tool:"Matrice d'assemblage",del:"Playbook du changement sur mesure",dur:"1 à 2 semaines",mis:"Le maximalisme : déployer les huit étapes de Kotter quand le diagnostic n'en montrait que deux manquantes."},
 {n:"Déployer par vagues",obj:"L'élan avant la couverture.",act:"Pilote avec une population crédible-mais-favorable, victoires rapides fabriquées dans les 60 premiers jours, cadence de gouvernance, résistance traitée comme une donnée.",tool:"Plan de vagues + registre des risques",del:"Feuille de route d'exécution, vivante",dur:"3 à 9 mois",mis:"Le lancement big-bang avec une « campagne » de communication au lieu d'une architecture de conversation."},
 {n:"Ancrer & mesurer",obj:"Faire en sorte que ça survive à votre départ.",act:"Métriques adoption / maîtrise / pérennité, incitations et rituels recâblés, capacité transférée aux relais internes.",tool:"Tableau de bord d'adoption",del:"Plan d'ancrage + passation de capacité",dur:"2 à 4 mois",mis:"Crier victoire à la mise en production. La mesure du sixième mois est le vrai verdict."}
];
