/* AUTO-EXTRACTED from the vanilla build. */
// @ts-nocheck
export const SIT_GROUPS = [
 {id:"exec", name:"Execution & adoption", desc:"The change exists on paper; reality is not following."},
 {id:"people", name:"People & emotions", desc:"The plan is fine; the humans were not consulted about their feelings."},
 {id:"structure", name:"Structure & growth", desc:"The organization itself is changing shape."},
 {id:"leadership", name:"Leadership & sponsorship", desc:"The problem sits above the org chart's waterline."}
];

export const SITS = {

stalled:{group:"exec", t:"Our transformation is losing steam",
 d:"Launched with fanfare, real energy for a quarter, then meetings thin out, milestones slip quietly, and the steering committee starts discussing other topics. Nobody killed it; it is just... fading.",
 root:"Usually a Kotter step-7 failure: victory was declared at the pilot, consolidation never happened, and the organization's immune system is quietly reabsorbing the change. Often compounded by quick wins that were promised but never engineered.",
 asm:[
  {fw:"kotter", why:"Steps 6 to 8 specifically: re-engineer visible wins, consolidate, anchor. The mobilization arc is broken exactly where Kotter predicted it breaks."},
  {fw:"adkar", why:"A barrier-point scan tells you whether the stall is organizational (momentum) or individual (people stuck at Desire or Ability). Treating one as the other wastes the relaunch."}],
 how:[
  "Forensic week: map what was actually completed against the original arc; identify the skipped step (it is almost always 6 or 7).",
  "Honest reckoning with the sponsor: relaunching without naming the stall publicly reads as denial and burns credibility.",
  "ADKAR pulse on two or three key populations to locate where individuals actually are.",
  "Relaunch on a deliberately smaller scope with one engineered, dated, visible win inside 60 days.",
  "Install consolidation governance: a standing review that treats regression as the default risk, not an anomaly."],
 watch:"Do not relaunch with a bigger announcement than the first launch. Quieter and truer beats louder.",
 svc:"Transformation Support"},

ghosttool:{group:"exec", t:"The new system nobody uses",
 d:"Deployed on time, training completed, help guides published. Usage curves say everything: a spike at go-live, then a slide back to spreadsheets, shadow tools and workarounds.",
 root:"Adoption problems are rarely training problems. The usual suspects: incentives that still reward the old way, workflows that make the new tool slower for the individual even if better for the organization, or identity (the tool devalues someone's hard-won expertise).",
 asm:[
  {fw:"adkar", why:"The spine. Barrier-point diagnosis by population: back office stuck at Ability needs practice environments; veterans stuck at Desire need the incentive and identity work, not more training."},
  {fw:"lewin", why:"Force Field Analysis on the daily workflow: what restraining forces make the old way easier? Removing one restraint beats three motivation campaigns."}],
 how:[
  "Stop all generic training immediately; it is treating the wrong element and breeding cynicism.",
  "ADKAR assessment segmented by population, not averaged: averages hide the story.",
  "Shadow three real users for a day each; find where the new tool loses to the old one in lived time and clicks.",
  "Fix the losing moments (integrations, defaults, shortcuts) and the incentive misalignments before asking again.",
  "Reinforcement phase: make the new way visibly count in reviews and recognition; measure demonstrated ability, not logins."],
 watch:"Login metrics lie. Measure task completion through the tool, not authentication.",
 svc:"Readiness Diagnostic"},

erp:{group:"exec", t:"Standardizing processes across units (ERP, shared services)",
 d:"Every unit swears its process is the exception that justifies keeping its way. The harmonization program is drowning in localization requests, and the business case erodes with each granted exception.",
 root:"Process attachment is identity and power in disguise: the local process is where local autonomy lives. The fight is rarely about the field mapping; it is about who decides.",
 asm:[
  {fw:"sevens", why:"The misalignment grid: harmonized Systems colliding with decentralized Structure and autonomy-flavored Shared Values is the classic 7-S contradiction. Name it before negotiating field by field."},
  {fw:"kotter", why:"A guiding coalition with real unit-level credibility is the only body that can legitimately arbitrate exceptions. Without it, every exception escalates to the top."},
  {fw:"adkar", why:"Per-unit adoption tracking once the target process is set; each unit will stall at a different element."}],
 how:[
  "Run the 7-S scan to surface the real contradiction (autonomy vs standardization) at leadership level, before any process workshop.",
  "Get an explicit leadership decision on the autonomy question: what is genuinely local, what is non-negotiably common. In writing.",
  "Build the exception-arbitration coalition with respected unit representatives inside it.",
  "Sequence units by readiness, not by size or politics; let an early credible unit debug the target.",
  "Track adoption per unit with ADKAR; publish the comparison gently: peer visibility does the pushing."],
 watch:"Every exception granted before the autonomy decision is a precedent you will fight for years.",
 svc:"Transformation Support"},

pivot:{group:"exec", t:"A strategy pivot nobody understands",
 d:"Leadership announced a new direction two quarters ago. Ask ten managers what it means for their team and you get ten answers, or worse, ten shrugs. Execution continues on the old strategy by inertia.",
 root:"A clarity failure, not a resistance problem. The pivot was communicated as a slogan, never translated into observable outcomes per unit. People cannot execute what they cannot picture.",
 asm:[
  {fw:"kotter", why:"Steps 3 and 4: the vision needs the five-minute test (sayable, memorable, specific), then communication through behavior and structure, not another town hall."},
  {fw:"bridges", why:"The 4 P's of new beginnings (Purpose, Picture, Plan, Part) as the translation grid for every team: each person needs their Part or the pivot stays abstract."}],
 how:[
  "Rewrite the pivot as an outcome statement that passes the three-managers test (three separate managers describe it consistently).",
  "Cascade workshops where each team translates the pivot into its own three concrete behavior changes: translation, not repetition.",
  "Kill visible artifacts of the old strategy (dashboards, targets, rituals) that silently contradict the new one.",
  "Leaders narrate their own Part first; abstraction from the top licenses abstraction below.",
  "90-day check: re-run the three-managers test as the success metric of the communication itself."],
 watch:"If the incentive plan still pays the old strategy, the pivot is fiction regardless of communication quality.",
 svc:"Framing Sprint"},

fatigue:{group:"people", t:"Change fatigue everywhere",
 d:"Third reorganization in four years, plus a new CRM, plus a rebrand. People say 'change fatigue' out loud in meetings now. New announcements get eye-rolls before the second slide.",
 root:"Not resistance: exhaustion. Absorption capacity is a finite resource that was spent without accounting. The organization has also learned that changes overlap and die, so rational actors wait them out.",
 asm:[
  {fw:"lewin", why:"Scale discipline: contained scopes with a real refreeze, so the organization re-learns that changes actually finish. Finishing is the medicine."},
  {fw:"curve", why:"Reading instrument for a population living in a chronic valley; calibrates what leaders should say and, mostly, stop saying."},
  {fw:"bridges", why:"Endings work for the changes that were never closed: unfinished transitions are open tabs consuming background memory."}],
 how:[
  "Portfolio audit first: list every change currently 'live' in the affected population. The number will embarrass someone; that is the point.",
  "Explicitly close or kill the zombies, with public endings: 'X is finished, here is what it gave us' or 'X is stopped, here is why'.",
  "Negotiate a change budget with leadership: what this population absorbs per quarter, enforced like a real budget.",
  "Run the next change at Lewin scale, finish it visibly, celebrate the finishing itself.",
  "Only then sequence the bigger waves, with the change budget as the pacing rule."],
 watch:"Announcing a 'change freeze' is itself a change announcement. Just quietly stop, close, and finish things.",
 svc:"Readiness Diagnostic"},

merger:{group:"people", t:"Two cultures at war post-merger",
 d:"The org chart merged eighteen months ago; the identities did not. Meetings split into 'us' and 'them', process debates are proxy wars, and the best people from the acquired side are quietly interviewing elsewhere.",
 root:"Unmourned identity loss dressed up as operational disagreement. Each side lost something real (status, rituals, ways of working) and nobody marked it, so the grief leaks out sideways as conflict.",
 asm:[
  {fw:"bridges", why:"The core treatment: endings work that names and honors what each side lost, before any 'one team' rhetoric, which currently reads as erasure."},
  {fw:"sevens", why:"Style and Staff are where merged organizations actually misalign; the scan localizes the friction beyond anecdote."},
  {fw:"curve", why:"The two populations are at different stages (acquirer often at integration, acquired often in the valley); communication must be calibrated per side."}],
 how:[
  "Loss analysis per population: what did each side concretely lose? Interviews, not surveys; people need to say it to a human.",
  "Facilitated endings sessions: each culture's history honored, artifacts kept, contributions named by the OTHER side.",
  "7-S scan on the combined entity to separate real operational misalignment from grief-driven conflict.",
  "Co-design two or three genuinely joint practices (not imposed from either side) as the first shared identity bricks.",
  "Track acquired-side regretted attrition monthly as the honest KPI of integration health."],
 watch:"Banning the old company names in conversation is erasure, not integration. Let the names retire on their own.",
 svc:"Transformation Support"},

survivors:{group:"people", t:"After the layoffs: leading the survivors",
 d:"The restructuring is done, the departed are gone, and leadership expects relief and refocus. Instead: guilt, fear, cynicism, and productivity that keeps sliding months after the announcement.",
 root:"Survivor syndrome: the remaining population has lost colleagues, trust and the belief that effort guarantees safety. The psychological contract is broken and nobody has acknowledged it, because leadership wants to 'move forward'.",
 asm:[
  {fw:"bridges", why:"This is the textbook endings situation: losses must be named (people, teams, the old implicit deal) before any new beginning is audible."},
  {fw:"curve", why:"Leaders need stage-calibrated communication: vision speeches into a grieving room cause the damage. Information, then empathy, then direction, in that order."}],
 how:[
  "Leadership acknowledges the losses explicitly and in person: the departed colleagues, the broken assumptions, the fear. No euphemisms ('rightsizing' insults the room).",
  "Managers hold one-to-one conversations with every survivor within 30 days; a script and training for these conversations, because most managers will avoid them.",
  "Rebuild the deal honestly: what the organization can and cannot promise now. False reassurance is fuel for the next cynicism wave.",
  "Neutral-zone structures: short-term goals, small wins, over-communication for a defined period.",
  "New beginnings only when the pulse says the room can hear them: purpose, picture, plan, and each person's part."],
 watch:"The productivity dip is grief, not laziness. Performance-managing it deepens it.",
 svc:"Sponsor & Leader Coaching"},

regulatory:{group:"people", t:"Regulatory change, imposed and unloved",
 d:"A new regulation lands with a deadline. Nobody in the organization chose it, many find it absurd, and the compliance program is met with the special resistance reserved for homework.",
 root:"Zero Desire by design: classic imposed change. The risk is malicious compliance: the letter of the rule, implemented in the most useless possible way, at maximum cost.",
 asm:[
  {fw:"bridges", why:"Brief but real endings work: name what the regulation kills (a freedom, a shortcut, a business line) instead of pretending it is an opportunity."},
  {fw:"adkar", why:"With Desire capped, over-invest in Awareness (why the regulator did this, honestly) and make Knowledge and Ability frictionless. Track it."},
  {fw:"curve", why:"Compressed curve: expect anger, do not argue with it, and calibrate messages to the stage."}],
 how:[
  "Honest framing: 'we did not choose this, here is what it costs us, here is why the regulator did it, here is how we make it cheap'. Adults respect honesty about imposition.",
  "Find the genuine silver linings without inventing fake ones (one real modernization opportunity beats five invented benefits).",
  "Make compliance the path of least resistance: defaults, automation, embedded controls; minimize the human effort tax.",
  "ADKAR tracking focused on Ability: is compliance actually doable in daily work, or does it collide with existing targets?",
  "Post-deadline: harvest and publicize what the constraint accidentally improved."],
 watch:"Rebranding an imposition as 'an exciting opportunity' costs leadership credibility it will need later.",
 svc:"Transformation Support"},

reorg:{group:"structure", t:"Reorganization: roles change, some disappear",
 d:"A new structure is coming: reporting lines redrawn, some roles merged, some eliminated, some created. The rumor mill is running at full capacity and productivity is already dipping before anything official.",
 root:"Uncertainty hurts more than bad news: people can adapt to a known loss but not to an ambiguous threat. Every week of vagueness is paid in engagement and in the best people's LinkedIn activity.",
 asm:[
  {fw:"bridges", why:"Endings and neutral zone are the whole game: the old structure must be closed properly and the in-between managed with temporary clarity."},
  {fw:"kotter", why:"A credible coalition and a communicable why: reorganizations without a believed rationale read as musical chairs or hidden downsizing."},
  {fw:"curve", why:"Different populations sit at different stages (winners, losers, spectators of the reorg); one message will be wrong for two of the three."}],
 how:[
  "Compress the uncertainty window: announce the why and the timeline immediately, individual impacts as fast as humanly possible.",
  "The why must pass the coffee-machine test: a rationale people can repeat without smirking.",
  "Managers equipped for the three conversations: better role, worse role, no role. Scripts, training, and no delegation of the hard ones upward.",
  "Neutral-zone kit for the transition months: interim decision rights, temporary goals, explicit 'how we work until D-day'.",
  "Close the old structure with an actual ending; day one of the new one gets the 4 P's, team by team."],
 watch:"Leaks beat announcements every time you wait. If the rumor mill is faster than you, you have already lost round one.",
 svc:"Transformation Support"},

scaling:{group:"structure", t:"Rapid growth is breaking how we work",
 d:"Headcount doubled in eighteen months. The informal magic that made the company work (everyone knew everyone, decisions over coffee) is gone, and the first processes feel like betrayal to the veterans.",
 root:"An identity transition disguised as an operational one: the veterans are grieving the company that was, and every new process is a symbol of that loss. Meanwhile the newcomers genuinely need the structure the veterans resent.",
 asm:[
  {fw:"bridges", why:"The veterans' loss is real (status, intimacy, influence) and must be honored, or they become the resistance leaders with maximum credibility."},
  {fw:"lewin", why:"Process by process: involve the people who lived the informal way in designing the formal one; people support what they help create."},
  {fw:"sevens", why:"Growth misaligns everything at once (Staff, Skills, Structure, Style); the scan prioritizes which alignment to fix first instead of fixing all badly."}],
 how:[
  "Name the transition publicly: 'the company you joined is becoming a different company, and that has costs'. Veterans first, in their own session.",
  "Give veterans an author role: they co-design the processes replacing their informal ways, and their war stories become the onboarding content.",
  "7-S scan to sequence: usually decision rights (Structure/Style) before tooling (Systems).",
  "Lewin-scale rollouts, one process at a time, refrozen properly, instead of a big 'professionalization program' that declares the past amateurish.",
  "Protect two or three rituals from the old world deliberately, and say so: continuity anchors make the rest of the change absorbable."],
 watch:"The phrase 'we need to professionalize' insults everyone who built the company. Ban it.",
 svc:"Framing Sprint"},

hybrid:{group:"structure", t:"The hybrid work model nobody agrees on",
 d:"Leadership wants people back; teams have built lives around flexibility; middle managers are stuck enforcing a policy they may not believe in. Every policy update reopens the war.",
 root:"A trust and control negotiation dressed as a logistics question. The real issues: how performance is measured (presence vs output), and whose preferences count. No badge policy fixes a measurement problem.",
 asm:[
  {fw:"lewin", why:"Force Field Analysis makes the real forces discussable (trust, cost, career fears, client demands) instead of proxy-warring over Tuesdays."},
  {fw:"adkar", why:"If a target model is chosen, managers are the make-or-break population: their Desire and Ability to lead differently is the actual change."},
  {fw:"curve", why:"For the population losing flexibility, this is a loss with a curve; pretending it is neutral logistics reads as contempt."}],
 how:[
  "Reframe from 'days in office' to 'what does this organization need presence FOR': explicit, activity-based reasoning.",
  "Force field session at leadership level: surface the real drivers (including the unspoken ones like real estate costs and control comfort).",
  "Decide, explain the reasoning honestly, and stop re-litigating: serial policy changes are worse than any single policy.",
  "Equip managers to lead by output: the actual capability change underneath the calendar question.",
  "Acknowledge the losers of the decision explicitly, whichever side they are on."],
 watch:"A policy announced, softened, hardened and softened again teaches everyone that lobbying beats adapting.",
 svc:"Sponsor & Leader Coaching"},

skills:{group:"structure", t:"Digital transformation meets skill fear",
 d:"Automation and AI are reshaping roles. Official comms speak of 'augmentation' and 'upskilling'; the corridors speak of 'who gets replaced'. Training programs launch into quiet dread.",
 root:"An existential Desire problem: people are being asked to enthusiastically build the thing they fear will obsolete them. Until the survival question is answered honestly, every training invitation reads as a countdown.",
 asm:[
  {fw:"adkar", why:"The spine, with brutal honesty at Awareness (what really changes for whom) and heavy investment at Desire before any Knowledge push."},
  {fw:"bridges", why:"Craft identity loss is real grief: 'my expertise mattered' is an ending that needs honoring, not a LinkedIn post about lifelong learning."},
  {fw:"kotter", why:"Quick wins recast: early, visible stories of colleagues who crossed the bridge and landed somewhere better."}],
 how:[
  "Answer the survival question first, honestly: which roles change, which shrink, what the organization commits to (redeployment, time, funding). Vagueness here poisons everything downstream.",
  "Endings work for the affected crafts: name what the expertise was worth; involve its holders in deciding what the machine should and should not do.",
  "Desire before Knowledge: no mass training until the WIIFM is real and individual (career paths, not slogans).",
  "Engineer crossing stories: first movers succeed visibly and narrate it themselves; peers believe peers.",
  "Ability means practice on real work with a safety net, not e-learning completion rates."],
 watch:"'People won't lose jobs to AI, but to people using AI' is a threat wearing a quote's clothing. Retire it.",
 svc:"Transformation Support"},

middlemgmt:{group:"leadership", t:"Middle management is quietly resisting",
 d:"The layer that translates strategy into daily work hasn't bought in, and won't say so out loud. Everything is nodded through in meetings, then nothing changes on the floor. The frozen middle.",
 root:"Usually rational, not cynical: middle managers absorb the workload of every change, lose autonomy or headcount in many, and are the last consulted. Their silent veto is the only power they have left in the process.",
 asm:[
  {fw:"adkar", why:"Desire is the blocked element, and it cannot be trained or mandated: it is built through involvement and honest WIIFM at this specific layer."},
  {fw:"kotter", why:"Coalition logic applied downward: recruit the most credible middle managers as co-designers, not messengers; the difference is everything."},
  {fw:"curve", why:"This layer is often further along the loss curve than anyone admits (they have seen the org chart implications first)."}],
 how:[
  "Diagnose the rationality: what does this change actually cost this layer (workload, autonomy, status, exposure)? Interviews, protected honesty.",
  "Involve before informing: the next design decision of the change is made WITH a group of credible middle managers, visibly.",
  "Address the real costs on the table: workload relief, decision rights, or honest acknowledgment when nothing can be given.",
  "Convert the informal leaders of the layer first; the frozen middle follows its own credible voices, not the executive floor.",
  "Make translation their job with authority attached: each manager owns the 'what it means for us', with real latitude."],
 watch:"Calling them 'the frozen middle' in any deck they might see confirms every suspicion they have about how they are viewed.",
 svc:"Readiness Diagnostic"},

nosponsor:{group:"leadership", t:"The sponsor is weak, absent, or missing",
 d:"The program has a steering committee, a budget and a plan, but when it needs a decision, an arbitration or a public defense, there is silence at the top. Everyone senses it, nobody says it.",
 root:"The single strongest predictor of failure, and the least discussable. Causes vary: the sponsor inherited the change, disagrees privately, is over-committed, or was never more than a name on a slide.",
 asm:[
  {fw:"kotter", why:"Steps 1 and 2 aimed UPWARD: the urgency case and the coalition are built for and around the leadership layer itself before anything moves below."},
  {fw:"adkar", why:"Run ADKAR on the sponsor personally: they are often stuck at their own Desire or Knowledge, and nobody dared diagnose it."}],
 how:[
  "Name it safely: a structured sponsorship assessment (the diagnostic's sponsorship dimension) puts numbers on what everyone senses, making it discussable without accusation.",
  "Diagnose the sponsor's own barrier: disagreement, competing priorities, fear of the political cost, or simple unawareness of the role's demands.",
  "Contract the role explicitly: what sponsoring THIS change requires in hours, decisions and public acts per month. Written.",
  "If the contract is refused: find the real sponsor (who actually loses if this fails?) or recommend pausing. Launching without sponsorship is scheduling a failure.",
  "If accepted: coach the behaviors, script the first three public acts, and monitor the sponsorship dimension monthly."],
 watch:"A consultant compensating for an absent sponsor becomes the sponsor, and everything collapses on their exit. Refuse that role.",
 svc:"Sponsor & Leader Coaching"},

newleader:{group:"leadership", t:"New leader, new direction, old organization",
 d:"A new executive arrives with a mandate and energy. Within weeks: a flurry of announced changes, a polite organization, and a quiet bet in the corridors on 'how long before this one gives up or leaves'.",
 root:"Two clocks out of sync: the leader's ambition runs on quarters, the organization's trust runs on years. The organization has survived leaders before; its default strategy is courteous waiting.",
 asm:[
  {fw:"kotter", why:"The full arc, but with step 2 before step 1 in practice: the coalition of respected insiders must co-own the urgency, or it is one person's opinion with a title."},
  {fw:"sevens", why:"A 7-S scan gives the new leader an evidence-based map instead of pattern-matching from the last company, the classic new-leader error."},
  {fw:"curve", why:"Ironically for the leader themselves: their arrival is a loss event for the organization (the previous era ended), and they are usually the last to see it."}],
 how:[
  "First 60 days: diagnose before declaring; the 7-S scan doubles as a listening tour that builds capital.",
  "Honor the past explicitly: what this organization did well before your arrival, said publicly and specifically. It costs nothing and buys the right to change things.",
  "Build the insider coalition before the big announcement; let respected veterans co-present the direction.",
  "One visible kept promise inside 90 days, however small: the organization is testing whether words mean things now.",
  "Sequence the ambition against the readiness profile, not against the leader's mandate clock."],
 watch:"Comparing the organization to your previous company, even favorably, is heard as 'you are raw material'.",
 svc:"Sponsor & Leader Coaching"},

culture:{group:"leadership", t:"We need to change the culture",
 d:"The values are on the wall, the workshops happened, the mugs were printed. Behavior is identical. Leadership concludes the program needs... more communication.",
 root:"Culture is the residue of what gets rewarded, tolerated and punished, not the content of the poster. If systems (promotion, incentives, who gets away with what) still pay the old culture, the old culture is rational.",
 asm:[
  {fw:"sevens", why:"Shared Values sit at the center of 7-S for a reason: the scan exposes which Systems and Style elements contradict the aspired culture. That contradiction IS the program."},
  {fw:"kotter", why:"Step 8 logic inverted into the design: anchoring mechanisms (hiring, promotion, rituals) become the levers, not the afterthought."},
  {fw:"adkar", why:"Behavior by behavior: culture change lands as specific new behaviors in specific moments, trackable like any adoption."}],
 how:[
  "Translate each aspired value into two or three observable behaviors in real moments (the meeting, the escalation, the failure debrief). No behavior, no program.",
  "Audit the contradictions: list where current systems reward the opposite of the poster. This list, not the values, is the change roadmap.",
  "Fix the loudest contradiction first and publicize the fix: one promotion decision aligned with the new culture teaches more than forty workshops.",
  "Leaders model the behaviors in observed moments; a single tolerated exception at the top resets the whole program.",
  "Measure behavior adoption in moments that matter, not survey agreement with value statements."],
 watch:"If the highest performer is a culture violator and keeps being one, the program is over, whatever the dashboards say.",
 svc:"Framing Sprint"}
};

export const SIT_GROUPS_FR = {
 exec:{name:"Exécution & adoption", desc:"Le changement existe sur le papier ; la réalité ne suit pas."},
 people:{name:"Humains & émotions", desc:"Le plan est bon ; on a oublié de consulter les humains sur leurs sentiments."},
 structure:{name:"Structure & croissance", desc:"C'est l'organisation elle-même qui change de forme."},
 leadership:{name:"Leadership & portage", desc:"Le problème se situe au-dessus de la ligne de flottaison de l'organigramme."}
};

export const SVC_FR = {"Framing Sprint":"Sprint de cadrage","Readiness Diagnostic":"Diagnostic de maturité","Transformation Support":"Accompagnement de transformation","Sponsor & Leader Coaching":"Coaching de sponsors & dirigeants"};

export const SITS_FR = {
stalled:{t:"Notre transformation s'essouffle",
 d:"Lancée en fanfare, une vraie énergie pendant un trimestre, puis les réunions se vident, les jalons glissent en silence et le comité de pilotage parle d'autre chose. Personne ne l'a tuée ; elle s'éteint.",
 root:"Le plus souvent un échec à l'étape 7 de Kotter : victoire proclamée au pilote, consolidation jamais faite, et le système immunitaire de l'organisation réabsorbe le changement. Souvent aggravé par des victoires rapides promises mais jamais fabriquées.",
 asm:[{fw:"kotter",why:"Étapes 6 à 8 spécifiquement : re-fabriquer des victoires visibles, consolider, ancrer. L'arc de mobilisation est cassé exactement là où Kotter l'avait prédit."},
      {fw:"adkar",why:"Un scan des points de blocage dit si la panne est organisationnelle (élan) ou individuelle (personnes bloquées à la Volonté ou à la Capacité). Confondre les deux gâche la relance."}],
 how:["Semaine forensique : cartographier ce qui a réellement été achevé face à l'arc initial ; identifier l'étape sautée (presque toujours la 6 ou la 7).",
      "Franchise avec le sponsor : relancer sans nommer publiquement la panne se lit comme du déni et brûle du crédit.",
      "Pouls ADKAR sur deux ou trois populations clés pour localiser où en sont vraiment les individus.",
      "Relancer sur un périmètre volontairement réduit, avec une victoire fabriquée, datée et visible sous 60 jours.",
      "Installer une gouvernance de consolidation : une revue permanente qui traite la régression comme le risque par défaut."],
 watch:"Ne pas relancer avec une annonce plus grosse que le premier lancement. Plus discret et plus vrai bat plus fort.", svc:"Accompagnement de transformation"},
ghosttool:{t:"Le nouveau système que personne n'utilise",
 d:"Déployé à l'heure, formations complétées, guides publiés. Les courbes d'usage disent tout : un pic au démarrage, puis la glissade vers les tableurs, les outils parallèles et les contournements.",
 root:"Les problèmes d'adoption sont rarement des problèmes de formation. Suspects habituels : des incitations qui récompensent encore l'ancienne façon, des flux qui rendent le nouvel outil plus lent pour l'individu, ou l'identité (l'outil dévalorise une expertise durement acquise).",
 asm:[{fw:"adkar",why:"La colonne vertébrale. Diagnostic des points de blocage par population : le back-office bloqué à la Capacité a besoin d'environnements d'entraînement ; les vétérans bloqués à la Volonté ont besoin du travail sur incitations et identité, pas de plus de formation."},
      {fw:"lewin",why:"Champ de forces sur le flux quotidien : quelles retenues rendent l'ancienne façon plus facile ? Retirer une retenue bat trois campagnes de motivation."}],
 how:["Arrêter immédiatement toute formation générique ; elle traite le mauvais élément et nourrit le cynisme.",
      "Évaluation ADKAR segmentée par population, jamais moyennée : les moyennes cachent l'histoire.",
      "Suivre trois utilisateurs réels une journée chacun ; trouver où le nouvel outil perd contre l'ancien en temps vécu et en clics.",
      "Corriger ces moments perdants (intégrations, valeurs par défaut, raccourcis) et les incitations désalignées avant de redemander.",
      "Phase de renforcement : faire compter visiblement la nouvelle façon dans les évaluations ; mesurer la capacité démontrée, pas les connexions."],
 watch:"Les métriques de connexion mentent. Mesurer les tâches accomplies dans l'outil, pas l'authentification.", svc:"Diagnostic de maturité"},
erp:{t:"Standardiser les processus entre entités (ERP, services partagés)",
 d:"Chaque entité jure que son processus est l'exception qui justifie sa façon de faire. Le programme d'harmonisation se noie dans les demandes de localisation, et le business case s'érode à chaque exception accordée.",
 root:"L'attachement au processus est de l'identité et du pouvoir déguisés : le processus local est là où vit l'autonomie locale. La bataille porte rarement sur le mapping des champs ; elle porte sur qui décide.",
 asm:[{fw:"sevens",why:"La grille des désalignements : des Systèmes harmonisés heurtant une Structure décentralisée et des Valeurs d'autonomie, c'est la contradiction 7-S classique. La nommer avant de négocier champ par champ."},
      {fw:"kotter",why:"Une coalition crédible au niveau des entités est le seul organe légitime pour arbitrer les exceptions. Sans elle, chaque exception remonte au sommet."},
      {fw:"adkar",why:"Suivi d'adoption par entité une fois la cible fixée ; chaque entité bloquera sur un élément différent."}],
 how:["Mener le scan 7-S pour faire remonter la vraie contradiction (autonomie contre standardisation) au niveau de la direction, avant tout atelier processus.",
      "Obtenir une décision explicite de la direction sur la question de l'autonomie : ce qui est réellement local, ce qui est commun sans négociation. Par écrit.",
      "Constituer la coalition d'arbitrage des exceptions avec des représentants respectés des entités.",
      "Séquencer les entités par maturité, pas par taille ni politique ; laisser une première entité crédible déboguer la cible.",
      "Suivre l'adoption par entité avec ADKAR ; publier la comparaison en douceur : la visibilité entre pairs fait le travail de pression."],
 watch:"Chaque exception accordée avant la décision d'autonomie est un précédent que vous combattrez pendant des années.", svc:"Accompagnement de transformation"},
pivot:{t:"Un pivot stratégique que personne ne comprend",
 d:"La direction a annoncé un nouveau cap il y a deux trimestres. Demandez à dix managers ce que ça change pour leur équipe : dix réponses, ou pire, dix haussements d'épaules. L'exécution continue sur l'ancienne stratégie par inertie.",
 root:"Un échec de clarté, pas de résistance. Le pivot a été communiqué comme un slogan, jamais traduit en résultats observables par entité. On ne peut pas exécuter ce qu'on ne peut pas se représenter.",
 asm:[{fw:"kotter",why:"Étapes 3 et 4 : la vision doit passer le test des cinq minutes (dicible, mémorable, spécifique), puis être communiquée par les comportements et la structure, pas par un town hall de plus."},
      {fw:"bridges",why:"Les 4 P des nouveaux départs (Purpose, Picture, Plan, Part) comme grille de traduction pour chaque équipe : sans son Part, le pivot reste abstrait."}],
 how:["Réécrire le pivot en énoncé de résultat qui passe le test des trois managers (trois managers séparés le décrivent de façon cohérente).",
      "Ateliers en cascade où chaque équipe traduit le pivot en trois changements de comportement concrets : traduction, pas répétition.",
      "Tuer les artefacts visibles de l'ancienne stratégie (tableaux de bord, objectifs, rituels) qui contredisent silencieusement la nouvelle.",
      "Les dirigeants racontent d'abord leur propre Part ; l'abstraction au sommet autorise l'abstraction en dessous.",
      "Contrôle à 90 jours : rejouer le test des trois managers comme métrique de la communication elle-même."],
 watch:"Si le plan d'incitation paie encore l'ancienne stratégie, le pivot est une fiction, quelle que soit la communication.", svc:"Sprint de cadrage"},
fatigue:{t:"La fatigue du changement, partout",
 d:"Troisième réorganisation en quatre ans, plus un nouveau CRM, plus un rebranding. « Fatigue du changement » se dit désormais à voix haute en réunion. Les annonces récoltent des soupirs avant la deuxième diapositive.",
 root:"Pas de la résistance : de l'épuisement. La capacité d'absorption est une ressource finie dépensée sans comptabilité. L'organisation a aussi appris que les changements se chevauchent et meurent ; les acteurs rationnels attendent qu'ils passent.",
 asm:[{fw:"lewin",why:"Discipline d'échelle : des périmètres contenus avec une vraie recristallisation, pour que l'organisation réapprenne que les changements se terminent. Terminer, c'est le médicament."},
      {fw:"curve",why:"Instrument de lecture pour une population en vallée chronique ; calibre ce que les dirigeants doivent dire et, surtout, arrêter de dire."},
      {fw:"bridges",why:"Travail des fins pour les changements jamais clos : les transitions inachevées sont des onglets ouverts qui consomment la mémoire de fond."}],
 how:["Audit de portefeuille d'abord : lister tous les changements « en cours » sur la population concernée. Le chiffre embarrassera quelqu'un ; c'est le but.",
      "Clore ou tuer explicitement les zombies, avec des fins publiques : « X est terminé, voici ce qu'il a donné » ou « X est arrêté, voici pourquoi ».",
      "Négocier un budget de changement avec la direction : ce que cette population absorbe par trimestre, tenu comme un vrai budget.",
      "Mener le prochain changement à l'échelle Lewin, le terminer visiblement, célébrer le fait même de terminer.",
      "Seulement ensuite, séquencer les vagues plus larges, avec le budget de changement comme règle de cadence."],
 watch:"Annoncer un « gel des changements » est en soi une annonce de changement. Arrêter, clore et terminer, discrètement.", svc:"Diagnostic de maturité"},
merger:{t:"Deux cultures en guerre après la fusion",
 d:"L'organigramme a fusionné il y a dix-huit mois ; les identités, non. Les réunions se coupent en « nous » et « eux », les débats de procédure sont des guerres par procuration, et les meilleurs de l'entité acquise passent des entretiens ailleurs, discrètement.",
 root:"Une perte d'identité non pleurée, déguisée en désaccord opérationnel. Chaque camp a perdu quelque chose de réel (statut, rituels, façons de faire) et personne ne l'a marqué ; le deuil fuit de côté, en conflit.",
 asm:[{fw:"bridges",why:"Le traitement central : un travail des fins qui nomme et honore ce que chaque camp a perdu, avant toute rhétorique « une seule équipe », qui sonne aujourd'hui comme un effacement."},
      {fw:"sevens",why:"Style et Staff sont les vrais points de désalignement des organisations fusionnées ; le scan localise la friction au-delà de l'anecdote."},
      {fw:"curve",why:"Les deux populations sont à des étapes différentes (l'acquéreur souvent à l'intégration, l'acquis souvent dans la vallée) ; la communication se calibre par camp."}],
 how:["Analyse des pertes par population : qu'a concrètement perdu chaque camp ? Des entretiens, pas des sondages ; les gens ont besoin de le dire à un humain.",
      "Séances de fins facilitées : l'histoire de chaque culture honorée, des objets conservés, les contributions nommées par l'AUTRE camp.",
      "Scan 7-S de l'entité combinée pour séparer le désalignement opérationnel réel du conflit porté par le deuil.",
      "Co-concevoir deux ou trois pratiques réellement communes (imposées par aucun camp) comme premières briques d'identité partagée.",
      "Suivre mensuellement l'attrition regrettée côté acquis : le KPI honnête de la santé de l'intégration."],
 watch:"Interdire les anciens noms d'entreprise dans la conversation est un effacement, pas une intégration. Laisser les noms prendre leur retraite seuls.", svc:"Accompagnement de transformation"},
survivors:{t:"Après les licenciements : diriger les survivants",
 d:"La restructuration est faite, les partants sont partis, la direction attend soulagement et recentrage. À la place : culpabilité, peur, cynisme, et une productivité qui glisse encore des mois après l'annonce.",
 root:"Le syndrome du survivant : la population restante a perdu des collègues, de la confiance, et la croyance que l'effort garantit la sécurité. Le contrat psychologique est rompu et personne ne l'a reconnu, parce que la direction veut « aller de l'avant ».",
 asm:[{fw:"bridges",why:"Le cas d'école des fins : les pertes doivent être nommées (les personnes, les équipes, l'ancien pacte implicite) avant qu'un nouveau départ soit audible."},
      {fw:"curve",why:"Les dirigeants ont besoin d'une communication calibrée par étape : les discours de vision dans une salle en deuil font les dégâts. Information, puis empathie, puis direction, dans cet ordre."}],
 how:["La direction reconnaît les pertes explicitement et en personne : les collègues partis, les certitudes brisées, la peur. Sans euphémismes (« rightsizing » insulte la salle).",
      "Les managers tiennent un entretien individuel avec chaque survivant sous 30 jours ; un guide et un entraînement pour ces conversations, car la plupart les éviteront.",
      "Reconstruire le pacte honnêtement : ce que l'organisation peut et ne peut pas promettre désormais. La fausse réassurance nourrit la vague de cynisme suivante.",
      "Structures de zone neutre : objectifs courts, petites victoires, sur-communication pendant une période définie.",
      "Les nouveaux départs seulement quand le pouls dit que la salle peut les entendre : purpose, picture, plan, et le rôle de chacun."],
 watch:"La baisse de productivité est du deuil, pas de la paresse. La gérer par la performance l'aggrave.", svc:"Coaching de sponsors & dirigeants"},
regulatory:{t:"Un changement réglementaire, subi et mal-aimé",
 d:"Une nouvelle réglementation tombe avec une échéance. Personne dans l'organisation ne l'a choisie, beaucoup la trouvent absurde, et le programme de conformité rencontre cette résistance spéciale réservée aux devoirs à la maison.",
 root:"Zéro Volonté, par construction : le changement subi classique. Le risque est la conformité de façade : la lettre de la règle, appliquée de la façon la plus inutile possible, au coût maximal.",
 asm:[{fw:"bridges",why:"Un travail des fins bref mais réel : nommer ce que la réglementation tue (une liberté, un raccourci, une ligne d'activité) au lieu de prétendre que c'est une opportunité."},
      {fw:"adkar",why:"La Volonté étant plafonnée, sur-investir la Conscience (pourquoi le régulateur a fait ça, honnêtement) et rendre Savoir et Capacité sans friction. Et le mesurer."},
      {fw:"curve",why:"Courbe compressée : attendre la colère, ne pas discuter avec elle, calibrer les messages à l'étape."}],
 how:["Cadrage honnête : « nous ne l'avons pas choisi, voici ce que ça nous coûte, voici pourquoi le régulateur l'a fait, voici comment le rendre bon marché ». Les adultes respectent l'honnêteté sur l'imposition.",
      "Trouver les vraies éclaircies sans en inventer de fausses (une opportunité réelle de modernisation vaut mieux que cinq bénéfices inventés).",
      "Faire de la conformité le chemin de moindre résistance : défauts, automatisation, contrôles intégrés ; réduire la taxe d'effort humain.",
      "Suivi ADKAR centré sur la Capacité : la conformité est-elle faisable au quotidien, ou heurte-t-elle les objectifs existants ?",
      "Après l'échéance : récolter et publier ce que la contrainte a accidentellement amélioré."],
 watch:"Rebaptiser une imposition en « opportunité enthousiasmante » coûte à la direction un crédit dont elle aura besoin plus tard.", svc:"Accompagnement de transformation"},
reorg:{t:"Réorganisation : des rôles changent, certains disparaissent",
 d:"Une nouvelle structure arrive : lignes hiérarchiques redessinées, rôles fusionnés, supprimés, créés. La machine à rumeurs tourne à plein régime et la productivité baisse déjà avant toute annonce officielle.",
 root:"L'incertitude blesse plus que la mauvaise nouvelle : on s'adapte à une perte connue, pas à une menace ambiguë. Chaque semaine de flou se paie en engagement et en activité LinkedIn des meilleurs.",
 asm:[{fw:"bridges",why:"Les fins et la zone neutre sont tout le sujet : clore proprement l'ancienne structure et gérer l'entre-deux avec une clarté temporaire."},
      {fw:"kotter",why:"Une coalition crédible et un pourquoi crédible : une réorganisation sans justification crue se lit comme des chaises musicales ou un dégraissage masqué."},
      {fw:"curve",why:"Les populations sont à des étapes différentes (gagnants, perdants, spectateurs) ; un message unique sera faux pour deux des trois."}],
 how:["Compresser la fenêtre d'incertitude : annoncer le pourquoi et le calendrier immédiatement, les impacts individuels aussi vite qu'humainement possible.",
      "Le pourquoi doit passer le test de la machine à café : une justification répétable sans sourire en coin.",
      "Équiper les managers pour les trois conversations : meilleur rôle, moins bon rôle, pas de rôle. Guides, entraînement, et pas de délégation des dures vers le haut.",
      "Kit de zone neutre pour les mois de transition : droits de décision provisoires, objectifs temporaires, « comment on travaille jusqu'au jour J » explicite.",
      "Clore l'ancienne structure par une vraie fin ; le premier jour de la nouvelle reçoit les 4 P, équipe par équipe."],
 watch:"Les fuites battent les annonces chaque fois que vous attendez. Si la rumeur va plus vite que vous, le premier round est déjà perdu.", svc:"Accompagnement de transformation"},
scaling:{t:"La croissance rapide casse nos façons de travailler",
 d:"Les effectifs ont doublé en dix-huit mois. La magie informelle qui faisait tourner l'entreprise (tout le monde connaissait tout le monde, les décisions autour d'un café) a disparu, et les premiers processus sonnent comme une trahison pour les anciens.",
 root:"Une transition d'identité déguisée en transition opérationnelle : les anciens font le deuil de l'entreprise d'avant, et chaque nouveau processus est un symbole de cette perte. Pendant ce temps, les nouveaux ont réellement besoin de la structure que les anciens détestent.",
 asm:[{fw:"bridges",why:"La perte des anciens est réelle (statut, intimité, influence) et doit être honorée, sinon ils deviennent les chefs de la résistance, avec un crédit maximal."},
      {fw:"lewin",why:"Processus par processus : impliquer ceux qui ont vécu l'informel dans la conception du formel ; on soutient ce qu'on a aidé à créer."},
      {fw:"sevens",why:"La croissance désaligne tout à la fois (Staff, Savoir-faire, Structure, Style) ; le scan priorise l'alignement à corriger en premier plutôt que tous, mal."}],
 how:["Nommer la transition publiquement : « l'entreprise que vous avez rejointe devient une autre entreprise, et cela a des coûts ». Les anciens d'abord, dans leur propre séance.",
      "Donner aux anciens un rôle d'auteur : ils co-conçoivent les processus qui remplacent leurs façons informelles, et leurs récits deviennent le contenu d'intégration.",
      "Scan 7-S pour séquencer : en général les droits de décision (Structure/Style) avant l'outillage (Systèmes).",
      "Déploiements à l'échelle Lewin, un processus à la fois, recristallisés proprement, plutôt qu'un grand « programme de professionnalisation » qui déclare le passé amateur.",
      "Protéger délibérément deux ou trois rituels de l'ancien monde, et le dire : les ancres de continuité rendent le reste absorbable."],
 watch:"La phrase « il faut nous professionnaliser » insulte tous ceux qui ont construit l'entreprise. À bannir.", svc:"Sprint de cadrage"},
hybrid:{t:"Le modèle hybride qui ne fait pas consensus",
 d:"La direction veut le retour au bureau ; les équipes ont construit leur vie autour de la flexibilité ; les managers intermédiaires appliquent une politique à laquelle ils ne croient pas forcément. Chaque mise à jour rouvre la guerre.",
 root:"Une négociation de confiance et de contrôle déguisée en question logistique. Les vrais sujets : comment la performance est mesurée (présence contre résultat), et quelles préférences comptent. Aucune politique de badge ne répare un problème de mesure.",
 asm:[{fw:"lewin",why:"L'analyse du champ de forces rend discutables les vraies forces (confiance, coûts, peurs de carrière, exigences clients) au lieu de guerres par procuration sur les mardis."},
      {fw:"adkar",why:"Si un modèle cible est choisi, les managers sont la population décisive : leur Volonté et leur Capacité à diriger autrement sont le vrai changement."},
      {fw:"curve",why:"Pour la population qui perd de la flexibilité, c'est une perte avec sa courbe ; prétendre que c'est de la logistique neutre sonne comme du mépris."}],
 how:["Recadrer de « jours au bureau » vers « pour quoi cette organisation a-t-elle besoin de présence » : un raisonnement explicite, par activité.",
      "Séance de champ de forces au niveau direction : faire émerger les vrais moteurs (y compris les non-dits : immobilier, confort de contrôle).",
      "Décider, expliquer honnêtement le raisonnement, et cesser de rejuger : les changements de politique en série sont pires que n'importe quelle politique.",
      "Équiper les managers pour diriger au résultat : le vrai changement de capacité sous la question de calendrier.",
      "Reconnaître explicitement les perdants de la décision, quel que soit leur camp."],
 watch:"Une politique annoncée, adoucie, durcie et re-adoucie enseigne à tous que le lobbying bat l'adaptation.", svc:"Coaching de sponsors & dirigeants"},
skills:{t:"La transformation digitale face à la peur des compétences",
 d:"L'automatisation et l'IA redessinent les rôles. La communication officielle parle d'« augmentation » et de « montée en compétence » ; les couloirs parlent de « qui sera remplacé ». Les programmes de formation se lancent dans une angoisse silencieuse.",
 root:"Un problème de Volonté existentiel : on demande aux gens de construire avec enthousiasme ce qui, craignent-ils, les rendra obsolètes. Tant que la question de survie n'a pas de réponse honnête, chaque invitation à se former sonne comme un compte à rebours.",
 asm:[{fw:"adkar",why:"La colonne vertébrale, avec une honnêteté brutale à la Conscience (ce qui change vraiment, pour qui) et un investissement massif à la Volonté avant tout Savoir."},
      {fw:"bridges",why:"La perte d'identité de métier est un vrai deuil : « mon expertise comptait » est une fin à honorer, pas un post LinkedIn sur l'apprentissage tout au long de la vie."},
      {fw:"kotter",why:"Les victoires rapides revisitées : des histoires précoces et visibles de collègues qui ont traversé le pont et atterri mieux."}],
 how:["Répondre d'abord à la question de survie, honnêtement : quels rôles changent, lesquels rétrécissent, ce que l'organisation s'engage à faire (redéploiement, temps, financement). Le flou empoisonne tout le reste.",
      "Travail des fins pour les métiers touchés : nommer ce que valait l'expertise ; impliquer ses détenteurs dans la décision de ce que la machine doit et ne doit pas faire.",
      "La Volonté avant le Savoir : pas de formation de masse tant que le « qu'est-ce que j'y gagne » n'est pas réel et individuel (des parcours, pas des slogans).",
      "Fabriquer des récits de traversée : les premiers réussissent visiblement et le racontent eux-mêmes ; les pairs croient les pairs.",
      "La Capacité, c'est de la pratique sur du vrai travail avec un filet, pas des taux de complétion e-learning."],
 watch:"« Vous ne perdrez pas votre emploi face à l'IA, mais face à quelqu'un qui l'utilise » est une menace habillée en citation. À retirer.", svc:"Accompagnement de transformation"},
middlemgmt:{t:"L'encadrement intermédiaire résiste en silence",
 d:"La couche qui traduit la stratégie en travail quotidien n'a pas adhéré, et ne le dira pas tout haut. Tout est approuvé d'un hochement de tête en réunion, puis rien ne change sur le terrain. Le milieu figé.",
 root:"Le plus souvent rationnel, pas cynique : les managers intermédiaires absorbent la charge de chaque changement, perdent de l'autonomie ou des effectifs dans beaucoup, et sont consultés en dernier. Leur veto silencieux est le seul pouvoir qui leur reste dans le processus.",
 asm:[{fw:"adkar",why:"La Volonté est l'élément bloqué, et elle ne se forme ni ne se décrète : elle se construit par l'implication et un « qu'est-ce que j'y gagne » honnête, à ce niveau précis."},
      {fw:"kotter",why:"La logique de coalition appliquée vers le bas : recruter les managers les plus crédibles comme co-concepteurs, pas comme messagers ; la différence est tout."},
      {fw:"curve",why:"Cette couche est souvent plus loin sur la courbe de perte qu'on ne l'admet (elle a vu les implications d'organigramme la première)."}],
 how:["Diagnostiquer la rationalité : que coûte réellement ce changement à cette couche (charge, autonomie, statut, exposition) ? Entretiens, honnêteté protégée.",
      "Impliquer avant d'informer : la prochaine décision de conception se prend AVEC un groupe de managers crédibles, visiblement.",
      "Mettre les vrais coûts sur la table : allègement de charge, droits de décision, ou reconnaissance honnête quand rien ne peut être donné.",
      "Convertir d'abord les leaders informels de la couche ; le milieu figé suit ses propres voix crédibles, pas l'étage exécutif.",
      "Faire de la traduction leur métier, avec de l'autorité : chaque manager possède le « ce que ça veut dire pour nous », avec une vraie latitude."],
 watch:"Les appeler « le milieu figé » dans un support qu'ils pourraient voir confirme tous leurs soupçons sur la façon dont on les regarde.", svc:"Diagnostic de maturité"},
nosponsor:{t:"Le sponsor est faible, absent ou introuvable",
 d:"Le programme a un comité de pilotage, un budget et un plan, mais quand il faut une décision, un arbitrage ou une défense publique, c'est le silence au sommet. Tout le monde le sent, personne ne le dit.",
 root:"Le prédicteur d'échec le plus puissant, et le moins discutable. Les causes varient : le sponsor a hérité du changement, est en désaccord en privé, est sur-engagé ailleurs, ou n'a jamais été qu'un nom sur une diapositive.",
 asm:[{fw:"kotter",why:"Étapes 1 et 2 dirigées VERS LE HAUT : le dossier d'urgence et la coalition se construisent pour et autour de la couche dirigeante elle-même, avant que rien ne bouge en dessous."},
      {fw:"adkar",why:"Faire l'ADKAR du sponsor lui-même : il est souvent bloqué à sa propre Volonté ou à son propre Savoir, et personne n'a osé le diagnostiquer."}],
 how:["Le nommer sans danger : une évaluation structurée du portage (la dimension sponsoring du diagnostic) met des chiffres sur ce que tout le monde sent, et le rend discutable sans accusation.",
      "Diagnostiquer le blocage du sponsor : désaccord, priorités concurrentes, peur du coût politique, ou simple méconnaissance des exigences du rôle.",
      "Contractualiser le rôle explicitement : ce que porter CE changement exige en heures, décisions et actes publics par mois. Par écrit.",
      "Si le contrat est refusé : trouver le vrai sponsor (qui perd réellement si ça échoue ?) ou recommander la pause. Lancer sans portage, c'est programmer un échec.",
      "S'il est accepté : coacher les comportements, scénariser les trois premiers actes publics, et suivre la dimension sponsoring chaque mois."],
 watch:"Un consultant qui compense un sponsor absent devient le sponsor, et tout s'effondre à son départ. Refuser ce rôle.", svc:"Coaching de sponsors & dirigeants"},
newleader:{t:"Nouveau dirigeant, nouveau cap, vieille organisation",
 d:"Un nouveau dirigeant arrive avec un mandat et de l'énergie. En quelques semaines : une rafale de changements annoncés, une organisation polie, et un pari discret dans les couloirs sur « combien de temps avant que celui-ci renonce ou parte ».",
 root:"Deux horloges désynchronisées : l'ambition du dirigeant tourne en trimestres, la confiance de l'organisation en années. L'organisation a déjà survécu à des dirigeants ; sa stratégie par défaut est l'attente courtoise.",
 asm:[{fw:"kotter",why:"L'arc complet, mais avec l'étape 2 avant l'étape 1 en pratique : la coalition d'initiés respectés doit co-porter l'urgence, sinon c'est l'opinion d'une personne avec un titre."},
      {fw:"sevens",why:"Un scan 7-S donne au nouveau dirigeant une carte fondée sur les preuves plutôt qu'un calquage de sa précédente entreprise, l'erreur classique du nouvel arrivant."},
      {fw:"curve",why:"Ironiquement pour le dirigeant lui-même : son arrivée est un événement de perte pour l'organisation (l'ère précédente est finie), et il est souvent le dernier à le voir."}],
 how:["60 premiers jours : diagnostiquer avant de déclarer ; le scan 7-S fait aussi office de tournée d'écoute qui construit du crédit.",
      "Honorer le passé explicitement : ce que cette organisation a bien fait avant votre arrivée, dit publiquement et précisément. Ça ne coûte rien et ça achète le droit de changer.",
      "Construire la coalition d'initiés avant la grande annonce ; laisser des anciens respectés co-présenter le cap.",
      "Une promesse visible tenue sous 90 jours, si petite soit-elle : l'organisation teste si les mots veulent dire quelque chose désormais.",
      "Séquencer l'ambition sur le profil de maturité, pas sur l'horloge du mandat."],
 watch:"Comparer l'organisation à votre entreprise précédente, même favorablement, s'entend comme « vous êtes de la matière première ».", svc:"Coaching de sponsors & dirigeants"},
culture:{t:"Nous devons changer la culture",
 d:"Les valeurs sont sur les murs, les ateliers ont eu lieu, les mugs sont imprimés. Les comportements sont identiques. La direction conclut que le programme a besoin de... plus de communication.",
 root:"La culture est le résidu de ce qui est récompensé, toléré et puni, pas le contenu de l'affiche. Si les systèmes (promotion, incitations, ce qu'on laisse passer) paient encore l'ancienne culture, l'ancienne culture est rationnelle.",
 asm:[{fw:"sevens",why:"Les Valeurs partagées sont au centre du 7-S pour une raison : le scan expose quels Systèmes et quel Style contredisent la culture visée. Cette contradiction EST le programme."},
      {fw:"kotter",why:"La logique de l'étape 8 inversée en conception : les mécanismes d'ancrage (recrutement, promotion, rituels) deviennent les leviers, pas l'arrière-pensée."},
      {fw:"adkar",why:"Comportement par comportement : le changement de culture atterrit en comportements précis dans des moments précis, traçables comme n'importe quelle adoption."}],
 how:["Traduire chaque valeur visée en deux ou trois comportements observables dans des moments réels (la réunion, l'escalade, le débrief d'échec). Pas de comportement, pas de programme.",
      "Auditer les contradictions : lister où les systèmes actuels récompensent l'inverse de l'affiche. Cette liste, pas les valeurs, est la feuille de route.",
      "Corriger d'abord la contradiction la plus bruyante et publiciser la correction : une décision de promotion alignée enseigne plus que quarante ateliers.",
      "Les dirigeants incarnent les comportements dans des moments observés ; une seule exception tolérée au sommet remet le programme à zéro.",
      "Mesurer l'adoption des comportements dans les moments qui comptent, pas l'accord de sondage avec des énoncés de valeurs."],
 watch:"Si le meilleur performeur viole la culture et continue, le programme est terminé, quoi que disent les tableaux de bord.", svc:"Sprint de cadrage"}
};
